import os
import pickle
from sklearn.linear_model import LogisticRegression
from sentence_transformers import SentenceTransformer

# Dictionary mapping intent labels to example user queries
# These are used as training data for intent classification
training_data = {
    "weather_now": [
        "what's the weather in Paris",
        "how's it outside in New York?",
        "do I need a jacket in Oslo?",
        "is it hot in Cairo?",
        "current weather Munich",
        "how's the weather today in Berlin?",
        "how cold is it in Moscow?",
        "weather report for Rome",
        "berlin weather",
        "berlin",
        "weather oslo",
        "how does it feel outside in Toronto?",
        "tell me the weather in Chicago",
        "what's the climate like in London?",
        "weather in Tokyo",
        "what's the weather like in Sydney?",
        "weather of Delhi",
    ],
    "temperature": [
        "temperature in London",
        "temperature now in Delhi",
        "what's the high and low in Tokyo?",
        "tell me the temperature in Sydney",
        "temp in Berlin",
        "temp paris",
        "what's the current temp in Rome?",
        "temperature reading in Amsterdam",
        "give me the temperature in Dubai",
        "what's the outdoor temperature in Vancouver?",
        "what temperature should I expect in Miami?",
        "tell me today's temperature in Los Angeles",
    ],
    "pressure": [
        "what's the pressure in London?",
        "atmospheric pressure in Rome",
        "pressure levels in Berlin?",
        "tell me the air pressure in Paris",
        "current pressure reading in Sydney",
        "how high is the pressure in Toronto?",
        "pressure update for Chicago",
        "what's the barometric pressure in New York?",
        "give me the pressure info for Mumbai",
        "air pressure level in Bangkok",
        "pressure stats for Berlin",
        "pressure reading in Tokyo",
        "can you check the air pressure in Dubai?",
        "how is the pressure around San Francisco?"
    ],
    "humidity": [
        "humidity in Madrid?",
        "how humid is it in Bangkok?",
        "moisture level in Miami",
        "humidity london",
        "what's the humidity in New York?",
        "tell me the humidity levels in Berlin",
        "how much moisture is in the air in Sydney?",
        "humidity percentage in Tokyo",
        "what's the dew point in Chicago?",
        "is the air dry or humid in Paris?",
        "what's the relative humidity in Rome?",
        "humidity conditions in Vancouver",
        "can you give me humidity stats for Dubai?",
        "tell me the humidity in Los Angeles",
    ],
    "visibility": [
        "visibility in Sydney?",
        "can I see clearly in LA?",
        "is it foggy in Zurich?",
        "how's visibility in London?",
        "what's the visibility distance in Berlin?",
        "tell me about visibility in New York",
        "is there fog in San Francisco?",
        "how clear is the air in Paris?",
        "visibility conditions in Tokyo",
        "can I see far in Moscow today?",
        "what's the fog forecast for Chicago?",
        "visibility rating for Mumbai",
        "is the visibility good in Toronto?",
        "tell me if it's misty in Amsterdam",
        "what's the visibility like in Dubai?",
    ],
    "wind": [
        "how windy is it in Chicago?",
        "wind speed in Amsterdam?",
        "is it breezy in Cape Town?",
        "wind berlin",
        "what's the wind velocity in Paris?",
        "tell me the wind gusts in New York",
        "how strong is the wind in London?",
        "wind forecast for Sydney",
        "is it calm or windy in Tokyo?",
        "wind direction in Mumbai",
        "how hard is the wind blowing in Toronto?",
        "what's the wind chill factor in Oslo?",
        "can you check the wind conditions in Dubai?",
        "how windy will it be today in Rome?",
        "wind speed measurement in Los Angeles",
    ],
    "cloudiness": [
        "cloud coverage in Prague",
        "is it cloudy in Vienna?",
        "cloudiness tokyo",
        "how cloudy is it in Paris?",
        "tell me the cloud cover in Berlin",
        "is the sky clear in London?",
        "cloud level in New York",
        "what's the cloud percentage in Sydney?",
        "is it overcast in Mumbai?",
        "are there many clouds in Chicago?",
        "sky condition in Dubai",
        "how much cloudiness is expected in Toronto?",
        "cloud cover info for Amsterdam",
        "is it partly cloudy in Los Angeles?"
    ],
    "rain": [
        "is it raining in Dublin?",
        "rainfall in Seattle?",
        "how much did it rain in Mumbai?",
        "rain mumbai",
        "tell me if it's raining in London",
        "rain chances for Berlin",
        "is rain expected in Paris?",
        "has it rained recently in Sydney?",
        "how heavy is the rain in Tokyo?",
        "rain accumulation in Chicago",
        "will it rain later in Mumbai?",
        "rain report for Dubai",
        "rain intensity in Toronto",
        "is there any rain expected in Amsterdam?",
    ],
    "snow": [
        "is it snowing in Moscow?",
        "snow level in Oslo?",
        "tell me about snow in New York",
        "how much snow is expected in Toronto?",
        "has it snowed in Chicago recently?",
        "snowfall amounts in Paris",
        "is there snow on the ground in Moscow?",
        "snow accumulation in Vancouver",
        "will it snow tomorrow in London?",
        "snow conditions in Tokyo",
        "is it snowing right now in Oslo?",
        "how deep is the snow in Zurich?",
        "snow alerts for Amsterdam",
        "tell me the snow report in Dubai",
    ],
    "precipitation": [
        "precipitation in Melbourne?",
        "any precipitation in Singapore?",
        "tell me the precipitation levels in New York",
        "is there precipitation expected in Paris?",
        "current precipitation in Berlin",
        "precipitation stats for Sydney",
        "how much precipitation fell in Tokyo?",
        "precipitation amount in Chicago",
        "will there be precipitation tomorrow?",
        "precipitation report for Mumbai",
        "precipitation probability in Toronto",
        "how heavy is the precipitation in Amsterdam?",
        "precipitation forecast for Dubai",
        "tell me the precipitation for Los Angeles",
    ],
    "forecast": [
        "3 day forecast for Toronto",
        "what’s the 5 day forecast in New York",
        "what's the forecast for the weekend in NYC",
        "can I get the weather forecast for Berlin?",
        "how's the week looking in Madrid?",
        "do I need an umbrella next week in Seattle?",
        "show me 5 day forecast for Toronto",
        "future weather in Amsterdam",
        "what's the forecast for tomorrow in Paris?",
        "tell me the weather prediction for Berlin",
        "weather outlook for this weekend",
        "forecast report for Tokyo",
        "how accurate is the weather forecast today?",
        "is it going to be sunny this week in London?",

    ],
    "hourly_forecast": [
        "hourly forecast in Paris",
        "hourly weather in Berlin",
        "hourly forecast for New York",
        "hourly weather report in Tokyo",
        "hour by hour forecast in Sydney",
        "what’s the weather hour by hour in Miami?",
        "give me the hourly weather update for Chicago",
        "can I get the hourly forecast for London?",
        "hourly temperature in Los Angeles",
        "hourly rain chances in Seattle",
        "what’s the wind like each hour in Berlin?",
        "show me the hourly forecast for Dubai",
        "hourly precipitation forecast for Toronto",
        "will it rain each hour today in Paris?",
        "hourly weather changes in Amsterdam",
    ],
    "sun_times": [
        "sunrise time in Paris",
        "when does the sun set in Berlin?",
        "when is sunrise in Berlin?",
        "what time is sunset in Mumbai?",
        "tell me the sunrise time in Istanbul",
        "sunset today in Chicago",
        "when does the sun rise in Dubai?",
        "sunrise and sunset time for Melbourne",
        "at what time is sunrise in Tokyo?",
        "tell me when the sun will set in London",
        "sunrise schedule for New York",
        "what time is dawn in Amsterdam?",
        "when will the sun rise tomorrow in Rome?",
        "sunset times for Seattle",
        "how long is the daylight in Paris today?",
    ],
    "greeting": [
        "hello",
        "hey",
        "hello there",
        "hallo",
        "hi there",
        "greetings",
        "howdy",
        "hi",
        "hey there",
        "good morning",
        "good evening",
        "yo",
        "hi bot",
        "what's up",
        "greetings, weather bot",
    ],
    "thanks": [
        "thanks",
        "thank you",
        "cheers",
        "appreciate it",
        "many thanks",
        "thanks a lot",
        "bye",
        "thank you very much",
        "thanks for your help",
        "thank you for your assistance",
        "goodbye",
        "see you later",
        "take care",
        "have a nice day",
        "see you around",
        "bye bye",
        "exit",
        "quit",
    ],
    "who_are_you": [
        "who are you",
        "what's your name",
        "can you tell me who you are",
        "tell me about yourself",
        "are you a bot?",
        "what do you do?",
        "can you introduce yourself?",
        "who created you?",
        "are you human or robot?",
        "what is your purpose?",
        "where do you come from?",
        "are you an AI assistant?",
        "can you tell me your background?",
        "what kind of bot are you?",
        "do you have a name?"
    ],
    "how_are_you": [
        "how are you",
        "how are you doing",
        "how's it going",
        "how do you feel",
        "are you okay?",
        "how's your day going?",
        "how do you do?",
        "what's up?",
        "how have you been?",
        "how's everything?",
        "are you feeling good?",
        "how's life treating you?",
        "how are things with you?",
        "are you functioning well?",
        "what's new with you?",
    ],
    "unknown": [
        "what's 2+2",
        "tell me a joke",
        "can you dance",
        "do you like pizza?",
        "do you know football?",
        "what's your favorite color",
        "who is the president",
        "what's the meaning of life?",
        "can you solve puzzles?",
        "do you like music?",
        "tell me something interesting",
        "what's your favorite movie?",
        "do you play games?",
        "can you sing?",
        "what's your favorite book?"
    ],
}

data = [(sentence, intent) for intent, sentences in training_data.items() for sentence in sentences]

texts, labels = zip(*data)

# Load pretrained sentence-transformers model
embedder = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Generate embeddings for all texts
X = embedder.encode(texts)

# Train a logistic regression classifier 
clf = LogisticRegression(max_iter=1000)
clf.fit(X, labels)

# Save the trained model and embedder name
MODEL_DIR = "models"
os.makedirs(MODEL_DIR, exist_ok=True)

# Save the model to file
with open(os.path.join(MODEL_DIR, "intent_model.pkl"), "wb") as f:
    pickle.dump(clf, f)

# Save the embedder name to file
with open(os.path.join(MODEL_DIR, "embedder_name.pkl"), "wb") as f:
    pickle.dump('paraphrase-MiniLM-L6-v2', f)

print("✅ Intent model and embedder saved in /models/")
